modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="rubymod"
version="1.0.0"
displayName="rubymod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Fred Brandibur, MCreator"

[[dependencies.rubymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




